let dirc = 0
basic.forever(function () {
    dirc = randint(0, 4)
    led.plotBrightness(dirc, 0, 255)
    basic.pause(100)
    led.plotBrightness(dirc, 1, 255)
    led.plotBrightness(dirc, 0, 150)
    basic.pause(100)
    led.plotBrightness(dirc, 2, 255)
    led.plotBrightness(dirc, 1, 150)
    led.plotBrightness(dirc, 0, 50)
    basic.pause(100)
    led.plotBrightness(dirc, 3, 255)
    led.plotBrightness(dirc, 2, 150)
    led.plotBrightness(dirc, 1, 50)
    led.plotBrightness(dirc, 0, 0)
    basic.pause(100)
    led.plotBrightness(dirc, 4, 255)
    led.plotBrightness(dirc, 3, 150)
    led.plotBrightness(dirc, 2, 50)
    led.plotBrightness(dirc, 1, 0)
    basic.pause(100)
    led.plotBrightness(dirc, 4, 150)
    led.plotBrightness(dirc, 3, 50)
    led.plotBrightness(dirc, 2, 0)
    basic.pause(100)
    led.plotBrightness(dirc, 4, 50)
    led.plotBrightness(dirc, 3, 0)
    basic.pause(100)
    led.plotBrightness(dirc, 4, 0)
})
